### PR TITLE
Update azure-stack-add-default-image.md

### PR DESCRIPTION
**Pull request by heoelri**
added Use-AzureRmProfile

### CODE REVIEW

**Comment by gosali** [comment]
Hi @heoelri , we are still in discussing, will update the decision later soon. 
  
Thanks for your support,
Microsoft C&E Localization Team

**Comment by v-radelg** [comment]
Hi @heoelri , we are still in discussing, will update the decision later soon. 
		
Thanks for your support,

Microsoft C&E Localization Team

**Comment by gosali** [comment]
Hi @heoelri , we are still in discussing, will update the decision later soon.

See: https://github.com/MicrosoftDocs/azure-docs-pr/pull/20041

Thanks for your support,

Microsoft C&E Localization Team

**Comment by gosali** [comment]
@heoelri,  Thank you for your feedback and suggestion! 
  
  We found that reported content has been updated and this change does not apply anymore, which is not fully aligned to our acceptance criterial, I am closing this PR. 
  
  Microsoft C&E Localization Team

**Pull request closed without merging**
