### PR TITLE
Fixed REST API links

### PR DESCRIPTION
**Pull request by abeckDev**
"List available machine sizes for resizing" and "List all virtual machine sizes for subscription" now redirects to the correct pages.

### CODE REVIEW

**Comment by abeckDev** [comment]
My Change can be a little bit confusing.

So please notice the following problems:

The link https://docs.microsoft.com/rest/api/compute/virtualmachines/virtualmachines-list-sizes-for-resizing seems to redirect to the page where the "resize vm sizes" are explained. 

But it redirect you to the page where "all the sizes for a subscriptions" are explained.

So basically the targets of both links are reversed:

https://docs.microsoft.com/rest/api/compute/virtualmachines/virtualmachines-list-sizes-for-resizing ---> List all sizes for a subscription. [Wrong]

https://docs.microsoft.com/rest/api/compute/virtualmachines/virtualmachines-list-sizes-region ---> List all sizes available for resizing on VM level. [Wrong]

I think my Change will be a temporary solutions but I would reccomend to change the target for both links.

**Comment by v-radelg** [comment]
Hello @abeckDev  , thank for your contribution. We are currently reviewing it. 

We will communicate the decision taken accordingly. Thanks for your time and support.  

Kind regards,  Microsoft C&E Localization Team

**Comment by gosali** [comment]
Hello @abeckDev , thank for your contribution. We are currently reviewing it.

We will communicate the decision taken accordingly. Thanks for your time and support.

Kind regards, Microsoft C&E Localization Team

**Comment by cynthn** [comment]
@abeckDev thank you for catching that issue! I've gone ahead and fixed this in the English version and our localization people should be able to make sure the fixes get into the translated versions (I think this might affect all of the languages). @SunnyDeng The fixes are in https://github.com/MicrosoftDocs/azure-docs-pr/pull/42196 and https://github.com/MicrosoftDocs/azure-docs-pr/pull/42195.

**Comment by SunnyDeng** [comment]
Great! Thanks @cynthn. BTW: could you please help to the author information of the metadata?
@carolinacmoravia with @cynthn updates, i think we can close this PR. if you still find issues, please file a new new. 
Thanks

**Comment by abeckDev** [comment]
Hi @cynthn and @SunnyDeng  I am glad that I could help.

Thanks for your support in this one. I will now close this PR.

**Pull request closed without merging**
